FundApp/FundApp/Models/Complaint.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FundApp.Models
{
    public class Complaint
    {
        [Key]
        public int ComplaintID { get; set; }

        [Display(Name="Название жалобы")]
        [Required]
        public string Title { get; set; }

        [Display(Name = "Описание жалобы")]
        [Required]
        public string Description { get; set; }

        [Display(Name = "Дата публикации жалобы")]
        [Required]
        public DateTime AppearingDate { get; set; }
              
        public bool IsHidden { get; set; }
        
        [Required]
        public virtual User Creator { get; set; }
                
        public virtual OrganisationDeptor OrganisationDeptor { get; set; }
        public virtual EcologicalProblem EcologicalProblem { get; set; }
    }
}

FundApp/FundApp/Models/Section.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Linq;
using System.Web;

namespace FundApp.Models
{
    public class Section
    {
        [Key]
        public int SectionID { get; set; }

        [Display(Name = "Название секции")]
        [Required]
        public string Title { get; set; }
        
        [Display(Name = "Описание секции")]
        [Required]
        public string Description { get; set; }
        
        [Display(Name = "Время старта занятий")]
        [Required]
        public DateTime StartLessonsTime { get; set; }
        
        [Display(Name = "Число участников")]
        public int ParticipantsCount { get; set; }
        
        [Display(Name = "Число мест")]
        public int SpotsCount { get; set; }
        
        [Display(Name="Число свободных мест")]
        public int FreeSpotsCount { get; set; }
        
        [Display(Name="Число занятий")]
        public int LessonsCount { get; set; }

        [Required]
        public virtual Ecologist Ecologist { get; set; }
        
        public virtual ICollection<RankUser> Participants { get; set; }

        public void CalculateFreeSpots()
        {
            FreeSpotsCount = SpotsCount - ParticipantsCount;
        }

        public void CalculateParticipantsCount()
        {
            if (Participants != null)
                ParticipantsCount = Participants.Count();
            else
                ParticipantsCount = 0;
        }
    }
}

FundApp/FundApp/Controllers/RoomUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FundApp.Models;

namespace FundApp.Controllers
{
    public class RoomUserController : Controller
    {
        FundContext db = new FundContext();

        public ActionResult UserRoom()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "User")
                return View();
            else
                return RedirectToAction("Http403", "Error");
        }

        #region Жалоба

        [HttpGet]
        public ActionResult Complaint()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "User")
                return View();
            else
                return RedirectToAction("Http403", "Error");
        }

        //создание и отправка жалобы
        [HttpPost]
        public ActionResult Complaint(Complaint complaint)
        {
            if (complaint != null)
            {
                complaint.Creator = db.Users.Find(Session["SystemUserID"]);
                db.Complaints.Add(complaint);
                db.SaveChanges();
            }
            return RedirectToAction("UserRoom");
        }

        #endregion

        #region Курсы

        public ActionResult Sections()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "User")
            {
                List<Section> sections = db.Sections.ToList();
                ViewBag.participant = db.RankUsers.Find(Session["SystemUserID"]);

                return View(sections);
            }
            else
                return RedirectToAction("Http403", "Error");
        }

        //регистрация на курсы
        public ActionResult RegisterOnSection(int sectionID)
        {
            var section = db.Sections.Find(sectionID);

            //Если свободные местра еще есть
            if (section.FreeSpotsCount > 0)
            {
                var participant = db.RankUsers.Find(Session["SystemUserID"]);

                section.Participants.Add(participant);
                //section.CalculateParticipantsCount();
                //section.CalculateFreeSpots();
                TryUpdateModel<Section>(section);
                db.Entry<Section>(section).State = System.Data.EntityState.Modified;

                db.SaveChanges();
            }

            return RedirectToAction("Sections");
        }

        //дерегистрация
        public ActionResult DeregisterFromSection(int sectionID)
        {
            var section = db.Sections.Find(sectionID);
            var participant = db.RankUsers.Find(Session["SystemUserID"]);

            section.Participants.Remove(participant);
            //section.CalculateParticipantsCount();
            //section.CalculateFreeSpots();
            TryUpdateModel<Section>(section);
            db.Entry<Section>(section).State = System.Data.EntityState.Modified;

            db.SaveChanges();

            return RedirectToAction("Sections");
        }

        #endregion
    }
}

FundApp/FundApp/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FundApp.Models;

namespace FundApp.Controllers
{
    public class SectionsController : Controller
    {
        FundContext db = new FundContext();

        public ActionResult SectionsPage()
        {
            return View(db.Sections.ToList());
        }

        //Запрос(поиск) по сущностям "Эколог" и "Секция"
        [HttpGet]
        public ActionResult SearchSection(string searchString, string ecologistName)
        {
            if (string.IsNullOrWhiteSpace(searchString) && string.IsNullOrWhiteSpace(ecologistName))
            {
                return View("SectionsPage", db.Sections.ToList());
            }

            int lessonsCount;
            int freeSpots;
            DateTime date;

            Int32.TryParse(searchString, out lessonsCount);
            Int32.TryParse(searchString, out freeSpots);
            DateTime.TryParse(searchString, out date);
            

            List<Section> sections = db.Ecologists.Where(e => (e.Surname.Contains(ecologistName) ||e.Name.Contains(ecologistName) || e.FatherName.Contains(ecologistName)))
                                                  .SelectMany(e => db.Sections.Where(s => (s.Ecologist == e && (s.Title.Contains(searchString) || s.Description.Contains(searchString) 
                                                                                            || s.FreeSpotsCount == freeSpots || s.LessonsCount == lessonsCount 
                                                                                            || (s.StartLessonsTime.Year == date.Year && s.StartLessonsTime.Month == date.Month && s.StartLessonsTime.Day == date.Day)))))
                                                  .ToList();
            /*
                       
            List<Section> sections = db.Sections.Where(n => (n.Title.Contains(searchString) || n.Description.Contains(searchString) 
                                                        || n.Ecologist.Name.Contains(searchString) || n.Ecologist.Surname.Contains(searchString) 
                                                        || n.Ecologist.FatherName.Contains(searchString) || n.LessonsCount == lessonsCount
                                                        || n.FreeSpotsCount == freeSpots || (n.StartLessonsTime.Year == d.Year && n.StartLessonsTime.Month == d.Month && n.StartLessonsTime.Day == d.Day))).ToList();*/
            
            return View("SectionsPage", sections);
        }
    }
}

FundApp/FundApp/Views/RoomUser/Complaint.cshtml
@model FundApp.Models.Complaint

@{
    ViewBag.Title = "CreateComplaint";
}

<h2 class="title">Создать жалобу</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.Title, new { @class="form-control", placeholder="Название..."})
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field form-item">
            @Html.TextAreaFor(model => model.Description, new { @class="form-control", placeholder="Описание..."})
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.AppearingDate)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.AppearingDate, new { @class="form-control", placeholder="Дата (dd.mm.yyyy)..."})
            @Html.ValidationMessageFor(model => model.AppearingDate)
        </div>

        <p>
            <input type="submit" class="btn btn-default form-item" value="Создать" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Вернуться", "UserRoom", null, new {@class="form-item btn btn-default"})
</div>

FundApp/FundApp/Views/RoomUser/Sections.cshtml
@model IEnumerable<FundApp.Models.Section>

@{
    ViewBag.Title = "Sections";
}

<h2 class="title">Экологические секции</h2>

@if (Model.Count() != 0)
{
    <table class="table table-striped table-condensed table-hover data-table table-bordered">
        <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Преподаватель</th>
                <th>Начало занятий</th>
                <th>Число занятий</th>
                <th>Число св. мест</th>
                <th>Регистрация</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var s in Model)
            {
                <tr>
                    <td>
                        @s.Title
                    </td>
                    <td>
                        @s.Description
                    </td>
                    <td>
                        @s.Ecologist.Surname @s.Ecologist.Name @s.Ecologist.FatherName
                    </td>
                    <td>
                        @s.StartLessonsTime.ToShortDateString()
                    </td>
                    <td>
                        @s.LessonsCount
                    </td>
                    <td>
                        @s.FreeSpotsCount
                    </td>
                    @if(!s.Participants.Contains(ViewBag.participant)) {
                        <td>
                            @Html.ActionLink("Зарегистрироваться", "RegisterOnSection", "RoomUser", new { sectionID = s.SectionID }, null)
                        </td>
                    }
                    else {
                        <td>
                            @Html.ActionLink("Дерегистрироваться", "DeregisterFromSection", "RoomUser", new { sectionID = s.SectionID }, null)
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>
        В настоящее время экологический фонд не проводит никаких курсов.
    </p>
}

FundApp/FundApp/Views/RoomUser/UserRoom.cshtml
@{
    ViewBag.Title = "UserRoom";
}

<h2 class="title">Кабинет пользователя</h2>

<table class="choice-group">
    <tr>
        <td class="choice-item">
            <h2>Создание жалобы</h2>
            <p>
                В данном блоке пользователю предлагается оформить жалобу на экологическое нарушение.
            </p>
            @Html.ActionLink("Пожаловаться", "Complaint", "RoomUser", new { @class = "btn btn-default"})
        </td>
        <td class="choice-item">
            <h2>Запись на курсы</h2>
            <p>
                В данном блоке пользователь может зарегистрироваться на курсы по экологическому воспитанию.
            </p>
            @Html.ActionLink("Подробнее...", "Sections", "RoomUser", new { @class = "btn btn-default"})
        </td>
    </tr>
</table>