FundApp/FundApp/Models/Complaint.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FundApp.Models
{
    public class Complaint
    {
        [Key]
        public int ComplaintID { get; set; }

        [Display(Name="Название жалобы")]
        [Required]
        public string Title { get; set; }

        [Display(Name = "Описание жалобы")]
        [Required]
        public string Description { get; set; }

        [Display(Name = "Дата публикации жалобы")]
        [Required]
        public DateTime AppearingDate { get; set; }
              
        public bool IsHidden { get; set; }
        
        [Required]
        public virtual User Creator { get; set; }
                
        public virtual OrganisationDeptor OrganisationDeptor { get; set; }
        public virtual EcologicalProblem EcologicalProblem { get; set; }
    }
}

FundApp/FundApp/Models/Council.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FundApp.Models
{
    public class Council
    {
        [Key]
        public int CouncilID { get; set; }
        
        [Display(Name="Название совета")]
        [Required]
        public string Title { get; set; }
        
        [Display(Name="Дата проведения")]
        [Required]
        public DateTime AssignmentDate { get; set; }

        [Display(Name = "Результат совета")]
        [Required]
        public bool CounsilResult { get; set; }

        [Display(Name = "Описание")]
        [Required]
        public string Description { get; set; }

        [Display(Name = "Экологическая проблема")]
        [Required]
        public virtual EcologicalProblem Problem { get; set; }
        
        public virtual ICollection<Ecologist> Ecologists { get; set; }
    }
}

FundApp/FundApp/Controllers/RoomEcologistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FundApp.Models;
using System.Diagnostics;

namespace FundApp.Controllers
{
    public class RoomEcologistController : Controller
    {
        FundContext db = new FundContext();

        public ActionResult EcologistRoom()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "Ecologist")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Http403", "Error");
            }
        }

        #region Жалобы пользователей

        public ActionResult Complaints()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "Ecologist")
            {
                List<Complaint> complaints = db.Complaints.Where(n => n.IsHidden == false).ToList(); //вернем только те жалобы, которым еще не были рассмотрены 
                return View(complaints);
            }
            else
            {
                return RedirectToAction("Http403", "Error");
            }
        }

        //Создание проблемы на базе жалобы
        [HttpGet]
        public ActionResult CreateProblem(int complaintID)
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "Ecologist")
            {
                ViewBag.complaintID = complaintID;
                return View();
            }
            else
            {
                return RedirectToAction("Http403", "Error");
            }
        }

        [HttpPost]
        public ActionResult CreateProblem(EcologicalProblem problem, int complaintID)
        {
            //Debug.WriteLine(complaintID);
            try
            {
                //одновременно "отклоняем" жалобу
                var complaint = db.Complaints.Find(complaintID);
                complaint.IsHidden = true;
                TryUpdateModel<Complaint>(complaint);
                db.Entry<Complaint>(complaint).State = System.Data.EntityState.Modified;
                db.SaveChanges();

                //сохраняем проблему
                problem.Creator = db.Ecologists.Find(Session["SystemUserID"]);
                problem.Complaint = db.Complaints.Find(complaintID);
                db.EcologicalProblems.Add(problem);
                db.SaveChanges();

                return RedirectToAction("Complaints");
            }
            catch {
                return View();
            }
        }
        
        //Отклонение жалобы
        public ActionResult DeclineComplaint(int complaintID)
        {
            //Debug.WriteLine(complaintID);
            var complaint = db.Complaints.Find(complaintID);

            if (complaint != null)
            {
                complaint.IsHidden = true;
                TryUpdateModel<Complaint>(complaint);
                db.Entry<Complaint>(complaint).State = System.Data.EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Complaints");
        }

        //Создание жалобы
        [HttpGet]
        public ActionResult CreateComplaint()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "Ecologist")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Http403", "Error");
            }
        }

        [HttpPost]
        public ActionResult CreateComplaint(Complaint complaint)
        {
            if (complaint != null)
            {
                complaint.IsHidden = false; //открываем проблему
                complaint.Creator = db.Users.Find(Session["SystemUserID"]);
                db.Complaints.Add(complaint);
                db.SaveChanges();
            }

            return RedirectToAction("Complaints");
        }
                
        #endregion

        #region Экологические советы
        
        public ActionResult Councils()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "Ecologist")
            {
                List<Council> councils = db.Councils.ToList();
                ViewBag.ecologist = db.Ecologists.Find(Session["SystemUserID"]);

                return View(councils);
            }
            else
            {
                return RedirectToAction("Http403", "Error");
            }
        }

        //регистрация на совет 
        public ActionResult RegisterOnCouncil(int councilID)
        {
            var council = db.Councils.Find(councilID);
            var ecologist = db.Ecologists.Find(Session["SystemUserID"]);

            council.Ecologists.Add(ecologist);
            TryUpdateModel<Council>(council);
            db.Entry<Council>(council).State = System.Data.EntityState.Modified;
            db.SaveChanges();
                        
            return RedirectToAction("Councils");
        }

        //дерегистрация с совета
        public ActionResult DeregisterFromCouncil(int councilID)
        {
            var council = db.Councils.Find(councilID);
            var ecologist = db.Ecologists.Find(Session["SystemUserID"]);

            council.Ecologists.Remove(ecologist);
            TryUpdateModel<Council>(council);
            db.Entry<Council>(council).State = System.Data.EntityState.Modified;
            db.SaveChanges();
            
            return RedirectToAction("Councils");
        }

        #endregion
    }
}

FundApp/FundApp/Views/RoomEcologist/Complaints.cshtml
@model IEnumerable<FundApp.Models.Complaint>

@{
    ViewBag.Title = "Complaints";
}

<h2 class="title">Жалобы пользователей</h2>

@if (Model.Count() != 0)
{
    <table class="table table-striped table-condensed table-hover data-table table-bordered">
        <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Дата публикования</th>
                <th>Создатель</th>
                <th>Отклонение</th>
                <th>Принятие</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var c in Model)
            {
                <tr>
                    <td>@c.Title</td>
                    <td>@c.Description</td>
                    <td>@c.AppearingDate</td>
                    <td>@c.Creator.Surname @c.Creator.Name @c.Creator.FatherName</td>
                    <td>@Html.ActionLink("Отклонить", "DeclineComplaint", new {complaintID = c.ComplaintID}, null)</td>
                    <td>@Html.ActionLink("Принять", "CreateProblem", new {complaintID = c.ComplaintID}, null)</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>
        В настоящее время жалоб на нарушения подано не было.
    </p>
}

@Html.ActionLink("Создать жалобу", "CreateComplaint", null, new { @class="btn btn-default"})

FundApp/FundApp/Views/RoomEcologist/Councils.cshtml
@model IEnumerable<FundApp.Models.Council>

@{
    ViewBag.Title = "Councils";
}

<h2 class="title">Экологические советы</h2>

@if (Model.Count() != 0)
{
    <table class="table table-striped table-condensed table-hover data-table table-bordered">
        <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Экологическая проблема</th>
                <th>Дата проведения</th>
                <th>Регистрация</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var c in Model)
            {
                <tr>
                    <td>@c.Title</td>
                    <td>@c.Description</td>
                    <td>@c.Problem.Title</td>
                    <td>@c.AssignmentDate.ToShortDateString()</td>
                    
                    @if (!c.Ecologists.Contains(ViewBag.ecologist))
                    {
                        <td>@Html.ActionLink("Зарегистрироваться", "RegisterOnCouncil", new { councilID = c.CouncilID }, null)</td>    
                    }
                    else
                    {
                        <td>@Html.ActionLink("Дерегистрироваться", "DeregisterFromCouncil", new { councilID = c.CouncilID }, null)</td>    
                    }
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>
        В настоящее время не запланировано ни одного экологического совета.
    </p>
}

FundApp/FundApp/Views/RoomEcologist/CreateComplaint.cshtml
@model FundApp.Models.Complaint

@{
    ViewBag.Title = "CreateComplaint";
}

<h2 class="title">Создание жалобы</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.Title, new { @class="form-control", placeholder="Название..."})
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        
        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.Description, new { @class="form-control", placeholder="Описание..."})
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.AppearingDate)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.AppearingDate, new { @class="form-control", placeholder="Дата (dd.mm.yyyy)..."})
            @Html.ValidationMessageFor(model => model.AppearingDate)
        </div>

        <p>
            <input type="submit" class="form-item btn btn-default" value="Создать" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Вернуться", "Complaints", null, new { @class="btn btn-default form-item"})
</div>

FundApp/FundApp/Views/RoomEcologist/CreateProblem.cshtml
@model FundApp.Models.EcologicalProblem

@{
    ViewBag.Title = "CreateProblem";
}

<h2 class="title">Создание проблемы</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>
        
        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.Title, new { @class="form-control", placeholder="Название..."})
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.Description, new { @class="form-control", placeholder="Описание..."})
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        
        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.RequiredSum)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.RequiredSum, new { @class="form-control", placeholder="Сумма..."})
            @Html.ValidationMessageFor(model => model.RequiredSum)
        </div>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.IsSolved)
        </div>
        <div class="editor-field form-item">
            @Html.EditorFor(model => model.IsSolved)
            @Html.ValidationMessageFor(model => model.IsSolved)
        </div>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.PublicationDate)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.PublicationDate, new { @class = "form-control", placeholder = "Дата (dd.mm.yyyy)..." })
            @Html.ValidationMessageFor(model => model.PublicationDate)
        </div>
        
        @Html.Hidden("complaintID", (object)ViewBag.complaintID)

        <p>
            <input type="submit" class="form-item btn btn-default" value="Создать" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Вернуться", "Complaints", null, new { @class="form-item btn btn-default"})
</div>

FundApp/FundApp/Views/RoomEcologist/EcologistRoom.cshtml
@{
    ViewBag.Title = "EcologistRoom";
}

<h2 class="title">Эколог</h2>

<table class="choice-group">
    <tr>
        <td class="choice-item">
            <h2>
                Экологические советы
            </h2>
            <p>
                В данном блоке экологу-специлисту предлагается возможность регистрации своего участия в экологических советах.
            </p>
            @Html.ActionLink("Перейти в раздел...", "Councils", "RoomEcologist", new { @class = "btn btn-default"})
        </td>

        <td class="choice-item">
            <h2>
                Жалобы на экологические нарушения 
            </h2>
            <p>
                В данном блоке администратору системы предлагается возможность рассмотрения жалоб пользователей на экологические нарушения, создания экологических проблем на основе проведенного мониторинга.
            </p>
            @Html.ActionLink("Перейти в раздел...", "Complaints", "RoomEcologist", new { @class = "btn btn-default"})
        </td>
    </tr>
</table>