FundApp/FundApp/Controllers/ProblemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FundApp.Models;

namespace FundApp.Controllers
{
    public class ProblemsController : Controller
    {
        FundContext db = new FundContext();

        public ActionResult ProblemsPage()
        {
            List<EcologicalProblem> problems = db.EcologicalProblems.ToList();
           
            return View(problems);
        }

        [HttpGet]
        public ActionResult SearchProblem(string searchString)
        {
            if (string.IsNullOrWhiteSpace(searchString))
            {
                return View("ProblemsPage", db.EcologicalProblems.ToList());
            }

            List<EcologicalProblem> requestedProblems = db.EcologicalProblems.Where(n => (n.Title.Contains(searchString) || n.Description.Contains(searchString))).ToList();

            return View("ProblemsPage", requestedProblems);
        }
    }
}

FundApp/FundApp/Views/Problems/ProblemsPage.cshtml
@model IEnumerable<FundApp.Models.EcologicalProblem>

@{
    ViewBag.Title = "ProblemsPage";
}


<h2>Экологические проблемы</h2>

<div class="search-block">
     @using (Html.BeginForm("SearchProblem", "Problems", FormMethod.Get, new { @class = "navbar-form navbar-right" }))
     {
        @Html.TextBox("searchString", null, new { @class = "form-control", placeholder = "Поиск..." })
        <button type="submit" class="btn btn-default">Искать</button>
     }
</div>

<div class="clear">
</div>

@if(Model.Count() != 0) {
    <table class="table table-bordered table-striped table-condensed table-hover data-table">
        <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Сумма</th>
                <th>Ход решения</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.Title</td>
                    <td>@p.Description</td>
                    <td>@p.RequiredSum р.</td>
                    <td>
                        @if(p.IsSolved) {
                            <span>Решена</span>
                        } else {
                            <span>Не решена</span>
                        }       
                    </td>
                </tr>
            }
        </tbody>
    </table>
} else {
    <p>
        Извините, вашему запросу не соответствуют никакие данные.   
    </p>
}