FundApp/FundApp/Controllers/RoomPartnerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FundApp.Models;

namespace FundApp.Controllers
{
    public class RoomPartnerController : Controller
    {
        FundContext db = new FundContext();

        public ActionResult PartnerRoom()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "Partner")
                return View();
            else
                return RedirectToAction("Http403", "Error");
        }

        //Создание жалобы
        [HttpGet]
        public ActionResult CreateComplaint()
        {
            if (Session["Role"] != null && Session["Role"].ToString() == "Partner")
                return View();
            else
                return RedirectToAction("Http403", "Error");
        }

        [HttpPost]
        public ActionResult CreateComplaint(Complaint complaint)
        {
            if (complaint != null)
            {
                complaint.Creator = db.Users.Find(Session["SystemUserID"]);
                db.Complaints.Add(complaint);
                db.SaveChanges();
            }
            return RedirectToAction("PartnerRoom");
        }

    }
}

FundApp/FundApp/Views/RoomPartner/CreateComplaint.cshtml
@model FundApp.Models.Complaint

@{
    ViewBag.Title = "CreateComplaint";
}

<h2 class="title">Создание жалобы</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend></legend>
       
        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.Title, new { @class="form-control", placeholder="Название жалобы"})
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.Description, new { @class="form-control", placeholder="Описание жалобы"})
            @Html.ValidationMessageFor(model => model.Description)
        </div>
                
        <div class="editor-label form-item form-item-title">
            @Html.LabelFor(model => model.AppearingDate)
        </div>
        <div class="editor-field form-item">
            @Html.TextBoxFor(model => model.AppearingDate, new { @class="form-control", placeholder="Дата (dd.mm.yyyy)..."})
            @Html.ValidationMessageFor(model => model.AppearingDate)
        </div>

        <p>
            <input type="submit" class="form-item btn btn-default" value="Создать" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Вернуться", "PartnerRoom", null, new {@class = "form-item btn btn-default"})
</div>

FundApp/FundApp/Views/RoomPartner/PartnerRoom.cshtml
@{
    ViewBag.Title = "PartnerRoom";
}

<h2 class="title">Кабинет организации-партнера</h2>

<table class="choice-group">
    <tr>
        <td class="choice-item">
            <h2>Жалоба</h2>
            <p>
                В данном блоке представителю организации-партнера предлагается оформить жалобу на экологическое нарушение
            </p>
            @Html.ActionLink("Пожаловаться", "CreateComplaint", "RoomPartner", new { @class = "btn btn-default"})
        </td>
    </tr>
</table>